vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|11 Aug 2004 19:30:11 -0000
vti_author:SR|www.dippikill.com
vti_modifiedby:SR|www.dippikill.com
vti_nexttolasttimemodified:TR|11 Aug 2004 19:30:11 -0000
vti_timecreated:TR|24 Mar 2005 21:46:24 -0000
vti_cachedparsepending:BX|true
vti_recalcupdatedate:TW|24 Mar 2005 21:46:24 -0000
vti_recalcupdateevntkey:SR|2005032421462400013599219987
vti_extenderversion:SR|5.0.2.2623
vti_syncwith_localhost\\c\:\\documents and settings\\owner\\my documents\\my webs\\dippikill site 04/c\:/documents and settings/owner/my documents/my webs/dippikill site 04:TR|11 Aug 2004 19:30:11 -0000
